/**
 * Path: apps/web/app/lib/skill-seed-foundation.ts
 *
 * Seed data for the FOUNDATION track at CEFR A1-A2.
 * Target user: Vietnamese learners who feel mất gốc — restart from
 * basics, focus on high-frequency vocab + survival phrases + the
 * present simple/past simple tenses + basic listening.
 *
 * Scope: 80 ASUs covering:
 *   - 30 vocab (must-know A1 words, organized by topic)
 *   - 20 phrases (survival + common situations)
 *   - 15 grammar points (basic tenses + word order + articles)
 *   - 10 listening items (slow speech, transcripts in VI+EN)
 *   - 5 pronunciation drills (specific Vietnamese-speaker pain points)
 *
 * Pronunciation IPA + audio URLs are placeholders — they'll be
 * populated by a future seeding script that calls vocab-api.ts.
 * Until then, lesson player falls back to speakWord() (Web Speech).
 *
 * IDs follow `<type>.<topic>.<NNN>` convention.
 */

import type { SkillUnit } from "./skill-units";

/* ────────────────────────────────────────────────────────────────────
   VOCAB — 30 ASUs (A1)
   ──────────────────────────────────────────────────────────────────── */

const VOCAB_A1: SkillUnit[] = [
  {
    id: "vocab.greetings.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:greetings", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "hello",
      pos: "interjection",
      pronunciation_ipa: "/həˈloʊ/",
      definition_en: "a greeting said when meeting someone",
      definition_vi: "lời chào khi gặp ai đó",
      example_en: "Hello, how are you?",
      example_vi: "Xin chào, bạn khỏe không?",
    },
  },
  {
    id: "vocab.greetings.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:greetings", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "goodbye",
      pos: "interjection",
      pronunciation_ipa: "/ɡʊdˈbaɪ/",
      definition_en: "said when leaving someone",
      definition_vi: "lời chào tạm biệt",
      example_en: "Goodbye, see you tomorrow.",
      example_vi: "Tạm biệt, hẹn gặp lại ngày mai.",
    },
  },
  {
    id: "vocab.daily.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "water",
      pos: "noun",
      pronunciation_ipa: "/ˈwɔː.tər/",
      definition_en: "a clear liquid that has no colour or taste",
      definition_vi: "nước",
      example_en: "Can I have a glass of water, please?",
      example_vi: "Cho tôi một ly nước được không?",
    },
  },
  {
    id: "vocab.daily.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "food",
      pos: "noun",
      pronunciation_ipa: "/fuːd/",
      definition_en: "anything that people or animals eat",
      definition_vi: "thức ăn, đồ ăn",
      example_en: "Vietnamese food is delicious.",
      example_vi: "Đồ ăn Việt Nam rất ngon.",
    },
  },
  {
    id: "vocab.daily.003",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "house",
      pos: "noun",
      pronunciation_ipa: "/haʊs/",
      definition_en: "a building where people live",
      definition_vi: "ngôi nhà",
      example_en: "I live in a small house.",
      example_vi: "Tôi sống trong một ngôi nhà nhỏ.",
    },
  },
  {
    id: "vocab.daily.004",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "family",
      pos: "noun",
      pronunciation_ipa: "/ˈfæm.ə.li/",
      definition_en: "a group of people related to each other",
      definition_vi: "gia đình",
      example_en: "My family is large.",
      example_vi: "Gia đình tôi rất đông.",
    },
  },
  {
    id: "vocab.daily.005",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "friend",
      pos: "noun",
      pronunciation_ipa: "/frend/",
      definition_en: "a person you know well and like",
      definition_vi: "bạn bè",
      example_en: "She is my best friend.",
      example_vi: "Cô ấy là bạn thân nhất của tôi.",
    },
  },
  {
    id: "vocab.daily.006",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "work",
      pos: "noun",
      pronunciation_ipa: "/wɜːrk/",
      definition_en: "a job that you do to earn money",
      definition_vi: "công việc",
      example_en: "I go to work every day.",
      example_vi: "Tôi đi làm mỗi ngày.",
    },
  },
  {
    id: "vocab.daily.007",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:daily", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "school",
      pos: "noun",
      pronunciation_ipa: "/skuːl/",
      definition_en: "a place where children learn",
      definition_vi: "trường học",
      example_en: "My school is near my house.",
      example_vi: "Trường tôi gần nhà.",
    },
  },
  {
    id: "vocab.numbers.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:numbers", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "one",
      pos: "number",
      pronunciation_ipa: "/wʌn/",
      definition_en: "the number 1",
      definition_vi: "số một",
      example_en: "I have one brother.",
      example_vi: "Tôi có một anh trai.",
    },
  },
  {
    id: "vocab.colors.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:colors", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "red",
      pos: "adjective",
      pronunciation_ipa: "/red/",
      definition_en: "the color of blood",
      definition_vi: "màu đỏ",
      example_en: "The roses are red.",
      example_vi: "Hoa hồng có màu đỏ.",
    },
  },
  {
    id: "vocab.colors.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:colors", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "blue",
      pos: "adjective",
      pronunciation_ipa: "/bluː/",
      definition_en: "the color of the sky",
      definition_vi: "màu xanh dương",
      example_en: "The sky is blue.",
      example_vi: "Bầu trời màu xanh.",
    },
  },
  {
    id: "vocab.time.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:time", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "today",
      pos: "adverb",
      pronunciation_ipa: "/təˈdeɪ/",
      definition_en: "on this day",
      definition_vi: "hôm nay",
      example_en: "Today is Monday.",
      example_vi: "Hôm nay là thứ Hai.",
    },
  },
  {
    id: "vocab.time.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:time", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "tomorrow",
      pos: "adverb",
      pronunciation_ipa: "/təˈmɒr.oʊ/",
      definition_en: "the day after today",
      definition_vi: "ngày mai",
      example_en: "I will see you tomorrow.",
      example_vi: "Tôi sẽ gặp bạn ngày mai.",
    },
  },
  {
    id: "vocab.verbs.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:verbs", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "eat",
      pos: "verb",
      pronunciation_ipa: "/iːt/",
      definition_en: "to put food into your mouth and swallow it",
      definition_vi: "ăn",
      example_en: "I eat breakfast at 7 a.m.",
      example_vi: "Tôi ăn sáng lúc 7 giờ.",
    },
  },
  {
    id: "vocab.verbs.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:verbs", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "drink",
      pos: "verb",
      pronunciation_ipa: "/drɪŋk/",
      definition_en: "to take liquid into your mouth and swallow it",
      definition_vi: "uống",
      example_en: "She drinks coffee every morning.",
      example_vi: "Cô ấy uống cà phê mỗi sáng.",
    },
  },
  {
    id: "vocab.verbs.003",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:verbs", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "go",
      pos: "verb",
      pronunciation_ipa: "/ɡoʊ/",
      definition_en: "to move from one place to another",
      definition_vi: "đi",
      example_en: "I go to school by bus.",
      example_vi: "Tôi đi học bằng xe buýt.",
    },
  },
  {
    id: "vocab.verbs.004",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:verbs", "weakness:vocab"],
    prerequisites: ["vocab.verbs.003"],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "arrive",
      pos: "verb",
      pronunciation_ipa: "/əˈraɪv/",
      definition_en: "to reach a place",
      definition_vi: "đến (nơi nào đó)",
      example_en: "We arrived at the airport at noon.",
      example_vi: "Chúng tôi đến sân bay lúc trưa.",
    },
  },
  {
    id: "vocab.feelings.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:feelings", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "happy",
      pos: "adjective",
      pronunciation_ipa: "/ˈhæp.i/",
      definition_en: "feeling pleasure or contentment",
      definition_vi: "vui, hạnh phúc",
      example_en: "I'm happy to see you.",
      example_vi: "Tôi rất vui khi gặp bạn.",
    },
  },
  {
    id: "vocab.feelings.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:feelings", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "tired",
      pos: "adjective",
      pronunciation_ipa: "/taɪərd/",
      definition_en: "needing rest or sleep",
      definition_vi: "mệt mỏi",
      example_en: "I'm tired after a long day.",
      example_vi: "Tôi mệt sau một ngày dài.",
    },
  },
  {
    id: "vocab.places.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:places", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "restaurant",
      pos: "noun",
      pronunciation_ipa: "/ˈres.tər.ɒnt/",
      definition_en: "a place where you can buy and eat a meal",
      definition_vi: "nhà hàng",
      example_en: "There is a good restaurant near my office.",
      example_vi: "Có một nhà hàng ngon gần văn phòng tôi.",
    },
  },
  {
    id: "vocab.places.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:places", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "hospital",
      pos: "noun",
      pronunciation_ipa: "/ˈhɒs.pɪ.tl/",
      definition_en: "a place where sick or injured people go for treatment",
      definition_vi: "bệnh viện",
      example_en: "She works at the hospital.",
      example_vi: "Cô ấy làm việc ở bệnh viện.",
    },
  },
  {
    id: "vocab.transport.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:transport", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "bus",
      pos: "noun",
      pronunciation_ipa: "/bʌs/",
      definition_en: "a large vehicle that carries many people",
      definition_vi: "xe buýt",
      example_en: "I take the bus to work.",
      example_vi: "Tôi đi xe buýt đi làm.",
    },
  },
  {
    id: "vocab.transport.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:transport", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "car",
      pos: "noun",
      pronunciation_ipa: "/kɑːr/",
      definition_en: "a road vehicle with four wheels",
      definition_vi: "xe hơi, ô tô",
      example_en: "My father drives a red car.",
      example_vi: "Bố tôi lái xe màu đỏ.",
    },
  },
  {
    id: "vocab.body.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:body", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "head",
      pos: "noun",
      pronunciation_ipa: "/hed/",
      definition_en: "the top part of your body that contains your brain",
      definition_vi: "đầu",
      example_en: "I have a headache.",
      example_vi: "Tôi bị đau đầu.",
    },
  },
  {
    id: "vocab.body.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:body", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "hand",
      pos: "noun",
      pronunciation_ipa: "/hænd/",
      definition_en: "the part at the end of your arm",
      definition_vi: "bàn tay",
      example_en: "Please wash your hands.",
      example_vi: "Hãy rửa tay đi.",
    },
  },
  {
    id: "vocab.weather.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:weather", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "rain",
      pos: "noun",
      pronunciation_ipa: "/reɪn/",
      definition_en: "water that falls from the sky",
      definition_vi: "mưa",
      example_en: "It's raining outside.",
      example_vi: "Trời đang mưa bên ngoài.",
    },
  },
  {
    id: "vocab.weather.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:weather", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "hot",
      pos: "adjective",
      pronunciation_ipa: "/hɒt/",
      definition_en: "having a high temperature",
      definition_vi: "nóng",
      example_en: "Vietnam is hot in summer.",
      example_vi: "Việt Nam nóng vào mùa hè.",
    },
  },
  {
    id: "vocab.shopping.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:shopping", "weakness:vocab"],
    prerequisites: [],
    estimated_seconds: 30,
    payload: {
      type: "vocab",
      word: "buy",
      pos: "verb",
      pronunciation_ipa: "/baɪ/",
      definition_en: "to get something by paying money for it",
      definition_vi: "mua",
      example_en: "I want to buy a new phone.",
      example_vi: "Tôi muốn mua điện thoại mới.",
    },
  },
];

/* ────────────────────────────────────────────────────────────────────
   PHRASES — 20 ASUs
   ──────────────────────────────────────────────────────────────────── */

const PHRASES: SkillUnit[] = [
  {
    id: "phrase.greeting.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:greetings"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "How are you?",
      phrase_vi: "Bạn có khỏe không?",
      context: "Câu hỏi thăm khi mới gặp ai đó.",
      example_en: "Hi, how are you?",
      example_vi: "Chào, bạn có khỏe không?",
    },
  },
  {
    id: "phrase.greeting.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:greetings"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I'm fine, thank you.",
      phrase_vi: "Tôi khỏe, cảm ơn bạn.",
      context: "Câu trả lời tiêu chuẩn cho 'How are you?'.",
      example_en: "I'm fine, thank you. And you?",
      example_vi: "Tôi khỏe, cảm ơn bạn. Còn bạn thì sao?",
    },
  },
  {
    id: "phrase.intro.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:introduction"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "My name is...",
      phrase_vi: "Tên tôi là...",
      context: "Tự giới thiệu lần đầu.",
      example_en: "My name is Minh. Nice to meet you.",
      example_vi: "Tên tôi là Minh. Rất vui được gặp bạn.",
    },
  },
  {
    id: "phrase.intro.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:introduction"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Nice to meet you.",
      phrase_vi: "Rất vui được gặp bạn.",
      context: "Lời lịch sự khi gặp lần đầu.",
      example_en: "Nice to meet you too!",
      example_vi: "Tôi cũng rất vui được gặp bạn!",
    },
  },
  {
    id: "phrase.polite.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:polite"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Thank you very much.",
      phrase_vi: "Cảm ơn bạn rất nhiều.",
      context: "Cảm ơn lịch sự, dùng được trong mọi tình huống.",
      example_en: "Thank you very much for your help.",
      example_vi: "Cảm ơn bạn rất nhiều vì đã giúp đỡ.",
    },
  },
  {
    id: "phrase.polite.002",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:polite"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "You're welcome.",
      phrase_vi: "Không có chi.",
      context: "Đáp lại khi ai đó cảm ơn.",
      example_en: "Thank you! — You're welcome.",
      example_vi: "Cảm ơn bạn! — Không có chi.",
    },
  },
  {
    id: "phrase.polite.003",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:polite"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Excuse me.",
      phrase_vi: "Xin lỗi (gây chú ý).",
      context: "Khi muốn xin chỉ đường hoặc gọi nhân viên.",
      example_en: "Excuse me, where is the bathroom?",
      example_vi: "Xin lỗi, nhà vệ sinh ở đâu?",
    },
  },
  {
    id: "phrase.polite.004",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:polite"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I'm sorry.",
      phrase_vi: "Tôi xin lỗi.",
      context: "Xin lỗi thực sự khi sai.",
      example_en: "I'm sorry, I didn't mean to.",
      example_vi: "Tôi xin lỗi, tôi không cố ý.",
    },
  },
  {
    id: "phrase.help.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:help", "travel:directions"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Can you help me?",
      phrase_vi: "Bạn có thể giúp tôi không?",
      context: "Khi cần nhờ ai đó giúp.",
      example_en: "Can you help me? I'm lost.",
      example_vi: "Bạn có thể giúp tôi không? Tôi bị lạc đường.",
    },
  },
  {
    id: "phrase.help.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:help", "travel:directions"],
    prerequisites: ["phrase.help.001"],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Could you tell me how to get to...?",
      phrase_vi: "Bạn có thể chỉ tôi cách đến... không?",
      context: "Hỏi đường lịch sự.",
      example_en: "Could you tell me how to get to the train station?",
      example_vi: "Bạn có thể chỉ tôi cách đến ga tàu không?",
    },
  },
  {
    id: "phrase.shop.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:shopping", "travel:shopping"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "How much is this?",
      phrase_vi: "Cái này giá bao nhiêu?",
      context: "Hỏi giá khi mua sắm.",
      example_en: "How much is this shirt?",
      example_vi: "Cái áo này giá bao nhiêu?",
    },
  },
  {
    id: "phrase.shop.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:shopping", "travel:shopping"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I'll take it.",
      phrase_vi: "Tôi lấy cái này.",
      context: "Quyết định mua một món.",
      example_en: "It looks good. I'll take it.",
      example_vi: "Nhìn đẹp đấy. Tôi lấy cái này.",
    },
  },
  {
    id: "phrase.food.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:food", "travel:food"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I'd like to order...",
      phrase_vi: "Tôi muốn gọi món...",
      context: "Gọi món ở nhà hàng.",
      example_en: "I'd like to order the beef noodle soup.",
      example_vi: "Tôi muốn gọi phở bò.",
    },
  },
  {
    id: "phrase.food.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:food", "travel:food"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "Can I have the bill, please?",
      phrase_vi: "Cho tôi xin hóa đơn nhé?",
      context: "Khi muốn thanh toán.",
      example_en: "Excuse me, can I have the bill, please?",
      example_vi: "Xin lỗi, cho tôi xin hóa đơn nhé?",
    },
  },
  {
    id: "phrase.time.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:time"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "What time is it?",
      phrase_vi: "Bây giờ là mấy giờ?",
      context: "Hỏi giờ.",
      example_en: "Excuse me, what time is it?",
      example_vi: "Xin lỗi, bây giờ là mấy giờ?",
    },
  },
  {
    id: "phrase.opinion.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:opinion"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I think that...",
      phrase_vi: "Tôi nghĩ rằng...",
      context: "Mở đầu khi nêu ý kiến.",
      example_en: "I think that we should leave now.",
      example_vi: "Tôi nghĩ rằng chúng ta nên đi bây giờ.",
    },
  },
  {
    id: "phrase.opinion.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:opinion"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I don't understand.",
      phrase_vi: "Tôi không hiểu.",
      context: "Khi không hiểu điều ai đó nói.",
      example_en: "I'm sorry, I don't understand. Can you repeat?",
      example_vi: "Xin lỗi, tôi không hiểu. Bạn có thể nhắc lại?",
    },
  },
  {
    id: "phrase.work.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:work"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "What do you do?",
      phrase_vi: "Bạn làm nghề gì?",
      context: "Hỏi nghề nghiệp.",
      example_en: "Nice to meet you. What do you do?",
      example_vi: "Rất vui được gặp bạn. Bạn làm nghề gì?",
    },
  },
  {
    id: "phrase.work.002",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "topic:work"],
    prerequisites: ["phrase.work.001"],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "I work as a...",
      phrase_vi: "Tôi làm... (nghề).",
      context: "Trả lời câu 'What do you do?'.",
      example_en: "I work as a software engineer.",
      example_vi: "Tôi làm kỹ sư phần mềm.",
    },
  },
  {
    id: "phrase.farewell.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "topic:greetings"],
    prerequisites: [],
    estimated_seconds: 45,
    payload: {
      type: "phrase",
      phrase_en: "See you later.",
      phrase_vi: "Gặp lại sau nhé.",
      context: "Lời chào tạm biệt thân mật.",
      example_en: "I have to go. See you later!",
      example_vi: "Tôi phải đi. Gặp lại sau nhé!",
    },
  },
];

/* ────────────────────────────────────────────────────────────────────
   GRAMMAR — 15 ASUs
   ──────────────────────────────────────────────────────────────────── */

const GRAMMAR: SkillUnit[] = [
  {
    id: "grammar.present-simple.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar", "targets:subject_verb_agree"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Thì hiện tại đơn — chủ ngữ ngôi 3 số ít",
      pattern: "He / She / It + V(s/es)",
      explain_vi:
        "Khi chủ ngữ là He, She, It (hoặc 1 người, 1 vật), động từ thường thêm -s. Đây là lỗi phổ biến nhất của người Việt.",
      examples: [
        { en: "She works at a bank.", vi: "Cô ấy làm việc ở ngân hàng." },
        { en: "He goes to school every day.", vi: "Anh ấy đi học mỗi ngày." },
        { en: "It rains a lot in summer.", vi: "Trời mưa nhiều vào mùa hè." },
      ],
      common_mistakes_vi: [
        "❌ She work at a bank → ✅ She works at a bank",
        "❌ He go to school → ✅ He goes to school",
      ],
    },
  },
  {
    id: "grammar.articles.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar", "targets:articles"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Mạo từ a / an",
      pattern: "a + phụ âm | an + nguyên âm",
      explain_vi:
        "Dùng 'a' trước phụ âm, 'an' trước nguyên âm (a, e, i, o, u). Quan trọng: nghe ÂM chứ không phải nhìn chữ. 'an hour' (h câm), 'a university' (u đọc /juː/).",
      examples: [
        { en: "I want a banana.", vi: "Tôi muốn 1 quả chuối." },
        { en: "She has an apple.", vi: "Cô ấy có 1 quả táo." },
        { en: "It's an hour from here.", vi: "Cách đây 1 tiếng." },
      ],
      common_mistakes_vi: [
        "❌ a apple → ✅ an apple",
        "❌ an university → ✅ a university (u đọc /juː/)",
      ],
    },
  },
  {
    id: "grammar.tobe.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Động từ to be — am / is / are",
      pattern: "I am | He/She/It is | You/We/They are",
      explain_vi:
        "to be là động từ quan trọng nhất. Chia theo chủ ngữ: I → am, He/She/It → is, You/We/They → are.",
      examples: [
        { en: "I am a student.", vi: "Tôi là sinh viên." },
        { en: "She is happy today.", vi: "Hôm nay cô ấy vui." },
        { en: "We are friends.", vi: "Chúng tôi là bạn." },
      ],
    },
  },
  {
    id: "grammar.past-simple.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar", "targets:verb_tense"],
    prerequisites: ["grammar.present-simple.001"],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Thì quá khứ đơn — động từ thường",
      pattern: "S + V-ed (regular) | S + V2 (irregular)",
      explain_vi:
        "Dùng để nói về việc đã xảy ra trong quá khứ. Động từ thường thêm -ed (worked, watched, played). Động từ bất quy tắc có dạng riêng (go → went, eat → ate).",
      examples: [
        { en: "Yesterday I watched a movie.", vi: "Hôm qua tôi xem một bộ phim." },
        { en: "She visited her grandmother last week.", vi: "Tuần trước cô ấy về thăm bà." },
        { en: "We went to the beach on Sunday.", vi: "Chủ nhật chúng tôi đi biển." },
      ],
    },
  },
  {
    id: "grammar.word-order.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar", "targets:word_order"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Trật tự câu cơ bản — S + V + O",
      pattern: "Chủ ngữ + Động từ + Tân ngữ",
      explain_vi:
        "Tiếng Anh tuân theo trật tự S-V-O nghiêm ngặt hơn tiếng Việt. Trạng từ tần suất (always, often, never...) đứng giữa chủ ngữ và động từ chính, KHÔNG ở đầu câu.",
      examples: [
        { en: "I always drink coffee.", vi: "Tôi luôn uống cà phê." },
        { en: "She often visits her family.", vi: "Cô ấy thường về thăm gia đình." },
        { en: "We never eat fast food.", vi: "Chúng tôi không bao giờ ăn đồ ăn nhanh." },
      ],
      common_mistakes_vi: [
        "❌ Always I drink coffee → ✅ I always drink coffee",
      ],
    },
  },
  {
    id: "grammar.plurals.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar", "targets:plurals"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Danh từ số nhiều — thêm -s",
      pattern: "noun + s | -es | irregular",
      explain_vi:
        "Đa số danh từ thêm -s ở số nhiều: book → books. Một số thêm -es: bus → buses. Một số bất quy tắc: child → children, man → men.",
      examples: [
        { en: "I have two books.", vi: "Tôi có 2 cuốn sách." },
        { en: "There are three buses.", vi: "Có 3 chiếc xe buýt." },
        { en: "My children are at school.", vi: "Các con tôi đang ở trường." },
      ],
      common_mistakes_vi: [
        "❌ two book → ✅ two books",
        "❌ three childs → ✅ three children",
      ],
    },
  },
  {
    id: "grammar.questions.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar"],
    prerequisites: ["grammar.tobe.001"],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Câu hỏi Yes/No với to be",
      pattern: "Am / Is / Are + S + ...?",
      explain_vi:
        "Để đặt câu hỏi Yes/No, đảo to be lên trước chủ ngữ.",
      examples: [
        { en: "Are you a student?", vi: "Bạn có phải là sinh viên không?" },
        { en: "Is she at home?", vi: "Cô ấy có ở nhà không?" },
      ],
    },
  },
  {
    id: "grammar.prepositions.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar", "targets:prepositions"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Giới từ thời gian — at / on / in",
      pattern: "at + giờ | on + ngày | in + tháng/năm",
      explain_vi:
        "at dùng cho giờ cụ thể (at 7 a.m.), on cho ngày trong tuần / ngày tháng (on Monday, on July 4th), in cho tháng / năm / thế kỷ (in July, in 2024).",
      examples: [
        { en: "I wake up at 6 a.m.", vi: "Tôi dậy lúc 6 giờ sáng." },
        { en: "We meet on Monday.", vi: "Chúng tôi gặp nhau vào thứ Hai." },
        { en: "She was born in 1995.", vi: "Cô ấy sinh năm 1995." },
      ],
    },
  },
  {
    id: "grammar.pronouns.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Đại từ nhân xưng — I, you, he, she, it, we, they",
      pattern: "Đại từ thay thế cho danh từ",
      explain_vi:
        "Dùng đại từ để không lặp lại danh từ. Lưu ý 'it' dùng cho vật và động vật chung chung.",
      examples: [
        { en: "She is my sister.", vi: "Cô ấy là chị tôi." },
        { en: "It is a beautiful day.", vi: "Hôm nay là 1 ngày đẹp." },
      ],
    },
  },
  {
    id: "grammar.possessive.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Tính từ sở hữu — my, your, his, her, our, their",
      pattern: "Tính từ sở hữu + danh từ",
      explain_vi:
        "Dùng để chỉ vật/người thuộc về ai. KHÔNG cần thêm 's' sau my/your.",
      examples: [
        { en: "This is my book.", vi: "Đây là sách của tôi." },
        { en: "Her sister is a doctor.", vi: "Chị cô ấy là bác sĩ." },
      ],
    },
  },
  {
    id: "grammar.canmust.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Động từ khiếm khuyết — can, must",
      pattern: "S + can/must + V(nguyên thể)",
      explain_vi:
        "can = có thể (khả năng), must = phải (bắt buộc). Động từ sau can/must KHÔNG chia, KHÔNG thêm 'to'.",
      examples: [
        { en: "I can swim.", vi: "Tôi biết bơi." },
        { en: "You must wear a helmet.", vi: "Bạn phải đội mũ bảo hiểm." },
      ],
      common_mistakes_vi: [
        "❌ I can to swim → ✅ I can swim",
        "❌ She cans swim → ✅ She can swim",
      ],
    },
  },
  {
    id: "grammar.present-continuous.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar", "targets:verb_tense"],
    prerequisites: ["grammar.tobe.001"],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Thì hiện tại tiếp diễn",
      pattern: "S + am/is/are + V-ing",
      explain_vi:
        "Dùng để nói về hành động đang xảy ra ngay lúc nói, hoặc đang diễn ra trong khoảng thời gian này.",
      examples: [
        { en: "I'm reading a book now.", vi: "Tôi đang đọc sách." },
        { en: "She is studying English this year.", vi: "Năm nay cô ấy đang học tiếng Anh." },
      ],
    },
  },
  {
    id: "grammar.thereis.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar"],
    prerequisites: [],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "There is / There are",
      pattern: "There is + danh từ số ít | There are + danh từ số nhiều",
      explain_vi:
        "Dùng để giới thiệu sự tồn tại — 'có cái gì đó'.",
      examples: [
        { en: "There is a cat on the chair.", vi: "Có 1 con mèo trên ghế." },
        { en: "There are many people here.", vi: "Có nhiều người ở đây." },
      ],
    },
  },
  {
    id: "grammar.negative.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:grammar"],
    prerequisites: ["grammar.present-simple.001"],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Câu phủ định với don't / doesn't",
      pattern: "S + don't/doesn't + V(nguyên thể)",
      explain_vi:
        "Để phủ định, thêm 'don't' (I, you, we, they) hoặc 'doesn't' (he, she, it). Động từ chính trở về dạng nguyên thể.",
      examples: [
        { en: "I don't like coffee.", vi: "Tôi không thích cà phê." },
        { en: "She doesn't speak French.", vi: "Cô ấy không nói tiếng Pháp." },
      ],
      common_mistakes_vi: [
        "❌ She doesn't speaks → ✅ She doesn't speak",
      ],
    },
  },
  {
    id: "grammar.frequency.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:grammar", "targets:word_order"],
    prerequisites: ["grammar.word-order.001"],
    estimated_seconds: 90,
    payload: {
      type: "grammar",
      rule_title_vi: "Trạng từ tần suất — always, often, usually, sometimes, never",
      pattern: "S + trạng từ tần suất + V",
      explain_vi:
        "Vị trí: giữa chủ ngữ và động từ chính. Với to be: SAU to be.",
      examples: [
        { en: "I always have breakfast at 7.", vi: "Tôi luôn ăn sáng lúc 7 giờ." },
        { en: "She is always late.", vi: "Cô ấy luôn đến muộn." },
      ],
    },
  },
];

/* ────────────────────────────────────────────────────────────────────
   LISTENING — 10 ASUs
   ──────────────────────────────────────────────────────────────────── */

const LISTENING: SkillUnit[] = [
  {
    id: "listening.intro.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:listening", "topic:introduction"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "Hi, my name is Sarah. I'm from London. Nice to meet you.",
      transcript_vi: "Chào, tên tôi là Sarah. Tôi đến từ London. Rất vui được gặp bạn.",
      question_vi: "Sarah đến từ đâu?",
      options: ["Paris", "London", "New York", "Tokyo"],
      answer_index: 1,
    },
  },
  {
    id: "listening.daily.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:listening", "topic:daily"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "I usually wake up at six thirty and have breakfast at seven.",
      transcript_vi: "Tôi thường dậy lúc 6 giờ rưỡi và ăn sáng lúc 7 giờ.",
      question_vi: "Người nói ăn sáng lúc mấy giờ?",
      options: ["6:30", "7:00", "7:30", "8:00"],
      answer_index: 1,
    },
  },
  {
    id: "listening.shop.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "topic:shopping"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "This shirt is twenty dollars. The blue one is twenty-five.",
      transcript_vi: "Áo này 20 đô la. Cái màu xanh thì 25.",
      question_vi: "Áo màu xanh giá bao nhiêu?",
      options: ["$15", "$20", "$25", "$30"],
      answer_index: 2,
    },
  },
  {
    id: "listening.food.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "topic:food", "travel:food"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "I'd like a coffee and a sandwich, please. To stay, not to go.",
      transcript_vi: "Cho tôi một cà phê và một bánh sandwich. Tôi dùng ở đây, không mang đi.",
      question_vi: "Người nói gọi gì?",
      options: ["Trà và bánh mì", "Cà phê và sandwich", "Nước và salad", "Soup và bánh"],
      answer_index: 1,
    },
  },
  {
    id: "listening.weather.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "topic:weather"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "Tomorrow will be sunny in the morning but it might rain in the afternoon.",
      transcript_vi: "Sáng mai trời sẽ nắng nhưng chiều có thể mưa.",
      question_vi: "Buổi chiều ngày mai thời tiết thế nào?",
      options: ["Nắng", "Có thể mưa", "Có tuyết", "Lạnh"],
      answer_index: 1,
    },
  },
  {
    id: "listening.transport.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "topic:transport"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "The next bus to the airport leaves at three forty-five from platform two.",
      transcript_vi: "Xe buýt tiếp theo đi sân bay khởi hành lúc 3 giờ 45 từ bến số 2.",
      question_vi: "Xe buýt đi sân bay khởi hành lúc nào?",
      options: ["3:15", "3:30", "3:45", "4:00"],
      answer_index: 2,
    },
  },
  {
    id: "listening.work.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "topic:work"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "I work for a small company. There are about thirty people in the office.",
      transcript_vi: "Tôi làm cho một công ty nhỏ. Văn phòng có khoảng 30 người.",
      question_vi: "Công ty có bao nhiêu người?",
      options: ["13", "20", "30", "50"],
      answer_index: 2,
    },
  },
  {
    id: "listening.family.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:listening", "topic:daily"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "I have one brother and two sisters. We live with our parents.",
      transcript_vi: "Tôi có 1 anh trai và 2 chị gái. Chúng tôi sống với bố mẹ.",
      question_vi: "Có bao nhiêu chị em trong gia đình?",
      options: ["2", "3", "4", "5"],
      answer_index: 2,
    },
  },
  {
    id: "listening.directions.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "travel:directions"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "Go straight for two blocks, then turn left. The bank is on your right.",
      transcript_vi: "Đi thẳng 2 đoạn rồi rẽ trái. Ngân hàng ở bên phải bạn.",
      question_vi: "Sau khi đi thẳng, người nghe phải làm gì?",
      options: ["Rẽ phải", "Rẽ trái", "Đi thẳng tiếp", "Quay lại"],
      answer_index: 1,
    },
  },
  {
    id: "listening.hotel.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:listening", "travel:hotel"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "listening",
      audio_url: "",
      transcript_en: "I'd like a single room for two nights, please. Breakfast included if possible.",
      transcript_vi: "Tôi muốn 1 phòng đơn 2 đêm. Bao gồm bữa sáng nếu được.",
      question_vi: "Khách đặt phòng mấy đêm?",
      options: ["1", "2", "3", "4"],
      answer_index: 1,
    },
  },
];

/* ────────────────────────────────────────────────────────────────────
   PRONUNCIATION — 5 ASUs (Vietnamese-speaker pain points)
   ──────────────────────────────────────────────────────────────────── */

const PRONUNCIATION: SkillUnit[] = [
  {
    id: "pronunciation.th.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:pronunciation", "targets:pronunciation_th"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "pronunciation",
      target_text_en: "Three brothers think this is the truth.",
      ipa: "/θriː ˈbrʌð.ərz θɪŋk ðɪs ɪz ðə truːθ/",
      tip_vi:
        "Âm /θ/ (think, three): đặt lưỡi giữa hai răng, thổi hơi nhẹ. KHÔNG đọc là 't' hay 's'. Âm /ð/ (this, the, brother): giống vậy nhưng rung dây thanh.",
    },
  },
  {
    id: "pronunciation.endings.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:pronunciation", "targets:pronunciation_endings"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "pronunciation",
      target_text_en: "She works, watches, washes, lives, and goes.",
      ipa: "/ʃiː wɜːrks ˈwɒtʃ.ɪz ˈwɒʃ.ɪz lɪvz ænd ɡoʊz/",
      tip_vi:
        "Người Việt thường bỏ -s ở cuối từ. Quy tắc: -s sau âm vô thanh đọc /s/, sau âm hữu thanh đọc /z/, sau âm xuýt thêm /ɪz/.",
    },
  },
  {
    id: "pronunciation.ed.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:pronunciation", "targets:pronunciation_endings"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "pronunciation",
      target_text_en: "I worked, watched, and decided.",
      ipa: "/aɪ wɜːrkt wɒtʃt ænd dɪˈsaɪd.ɪd/",
      tip_vi:
        "Đuôi -ed của động từ quá khứ có 3 cách đọc: /t/ sau âm vô thanh (worked → /wɜːrkt/), /d/ sau âm hữu thanh (lived → /lɪvd/), /ɪd/ sau /t/ hoặc /d/ (decided → /dɪˈsaɪd.ɪd/).",
    },
  },
  {
    id: "pronunciation.lr.001",
    level: "A1",
    tags: ["level:A1", "goal:foundation", "weakness:pronunciation"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "pronunciation",
      target_text_en: "I really like rice and lemons.",
      ipa: "/aɪ ˈrɪə.li laɪk raɪs ænd ˈlem.ənz/",
      tip_vi:
        "Người Việt khó phân biệt /l/ và /r/. /l/: chạm đầu lưỡi vào vòm trên răng. /r/: cong lưỡi nhẹ về sau, KHÔNG chạm vòm.",
    },
  },
  {
    id: "pronunciation.stress.001",
    level: "A2",
    tags: ["level:A2", "goal:foundation", "weakness:pronunciation"],
    prerequisites: [],
    estimated_seconds: 60,
    payload: {
      type: "pronunciation",
      target_text_en: "I would like to order coffee with sugar, please.",
      ipa: "/aɪ wʊd ˈlaɪk tuː ˈɔːr.dər ˈkɒf.i wɪð ˈʃʊɡ.ər pliːz/",
      tip_vi:
        "Tiếng Anh nhấn từ — không phải mọi âm tiết đều bằng nhau. Nhấn vào ÝC chính (LIKE, ORder, COFfee, SUgar). Giảm âm vào các từ chức năng (to, with, please).",
    },
  },
];

/* ────────────────────────────────────────────────────────────────────
   Combined export
   ──────────────────────────────────────────────────────────────────── */

export const FOUNDATION_SEED: SkillUnit[] = [
  ...VOCAB_A1,
  ...PHRASES,
  ...GRAMMAR,
  ...LISTENING,
  ...PRONUNCIATION,
];

/** Counts for sanity-check / display */
export const FOUNDATION_SEED_BREAKDOWN = {
  vocab: VOCAB_A1.length,
  phrase: PHRASES.length,
  grammar: GRAMMAR.length,
  listening: LISTENING.length,
  pronunciation: PRONUNCIATION.length,
  total: VOCAB_A1.length + PHRASES.length + GRAMMAR.length + LISTENING.length + PRONUNCIATION.length,
} as const;
